import { useState } from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 35,
    fontSize: 11,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
    color: '#111827',
  },

  cover: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    textAlign: 'center',
  },

  title: {
    fontSize: 30,
    marginBottom: 12,
    fontWeight: 'bold',
    color: '#0f172a',
  },

  subtitle: {
    fontSize: 16,
    marginBottom: 30,
    color: '#334155',
  },

  section: {
    marginBottom: 22,
  },

  heading: {
    fontSize: 18,
    marginBottom: 10,
    color: '#0369a1',
    fontWeight: 'bold',
    borderBottom: '1 solid #0ea5e9',
    paddingBottom: 5,
  },

  text: {
    lineHeight: 1.8,
    marginBottom: 8,
  },

  table: {
    width: '100%',
    border: '1 solid #cbd5e1',
    marginTop: 10,
  },

  row: {
    flexDirection: 'row',
  },

  cellHeader: {
    width: '50%',
    backgroundColor: '#0f172a',
    color: '#ffffff',
    padding: 8,
    borderRight: '1 solid #ffffff',
    fontWeight: 'bold',
  },

  cell: {
    width: '50%',
    padding: 8,
    borderRight: '1 solid #cbd5e1',
    borderTop: '1 solid #cbd5e1',
  },

  footer: {
    marginTop: 40,
    fontSize: 10,
    color: '#64748b',
    textAlign: 'center',
  },
});

const DPRDocument = ({
  businessName,
  ownerName,
  businessType,
  location,
  projectCost,
  loanAmount,
  turnover,
}: any) => (
  <Document>

    {/* COVER PAGE */}
    <Page size="A4" style={styles.page}>
      <View style={styles.cover}>
        <Text style={styles.title}>{businessName}</Text>

        <Text style={styles.subtitle}>
          Detailed Project Report (DPR)
        </Text>

        <Text style={styles.text}>
          Prepared for MSME / PMEGP / Mudra / Bank Loan
        </Text>

        <Text style={styles.text}>
          Generated by Business Partner AI
        </Text>

        <Text style={styles.text}>
          Founder: Akash Agnihotri
        </Text>
      </View>
    </Page>

    {/* MAIN PAGE */}
    <Page size="A4" style={styles.page}>

      {/* EXECUTIVE SUMMARY */}
      <View style={styles.section}>
        <Text style={styles.heading}>Executive Summary</Text>

        <Text style={styles.text}>
          {businessName} is a modern and scalable {businessType}
          business proposed in {location}. The project aims to create
          a profitable and sustainable business model with long-term
          growth opportunities.
        </Text>

        <Text style={styles.text}>
          This report has been prepared for bank loan approval,
          financial planning, investor presentation, and MSME
          registration support.
        </Text>
      </View>

      {/* PROJECT DETAILS */}
      <View style={styles.section}>
        <Text style={styles.heading}>Project Details</Text>

        <View style={styles.table}>

          <View style={styles.row}>
            <Text style={styles.cellHeader}>Particular</Text>
            <Text style={styles.cellHeader}>Details</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Business Name</Text>
            <Text style={styles.cell}>{businessName}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Owner Name</Text>
            <Text style={styles.cell}>{ownerName}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Business Type</Text>
            <Text style={styles.cell}>{businessType}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Location</Text>
            <Text style={styles.cell}>{location}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Project Cost</Text>
            <Text style={styles.cell}>₹ {projectCost}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Loan Requirement</Text>
            <Text style={styles.cell}>₹ {loanAmount}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.cell}>Expected Turnover</Text>
            <Text style={styles.cell}>₹ {turnover}</Text>
          </View>

        </View>
      </View>

      {/* MARKET ANALYSIS */}
      <View style={styles.section}>
        <Text style={styles.heading}>Market Analysis</Text>

        <Text style={styles.text}>
          The demand for {businessType} businesses is growing rapidly
          across India due to increasing consumer demand, digital
          adoption, and changing market trends.
        </Text>

        <Text style={styles.text}>
          The project has strong future scalability and revenue
          potential in both online and offline markets.
        </Text>
      </View>

      {/* FINANCIAL ANALYSIS */}
      <View style={styles.section}>
        <Text style={styles.heading}>Financial Analysis</Text>

        <Text style={styles.text}>
          Total project cost is estimated at ₹ {projectCost}. The
          promoter seeks financial support of ₹ {loanAmount}.
        </Text>

        <Text style={styles.text}>
          The expected annual turnover is projected at ₹ {turnover}
          with stable profit margins and increasing business growth.
        </Text>

        <Text style={styles.text}>
          Break-even is expected within the first 18–24 months of
          operations.
        </Text>
      </View>

      {/* CONCLUSION */}
      <View style={styles.section}>
        <Text style={styles.heading}>Conclusion</Text>

        <Text style={styles.text}>
          Based on the business potential, projected financials,
          operational strategy, and market demand, this project is
          financially viable and recommended for bank funding under
          MSME / PMEGP / Mudra schemes.
        </Text>
      </View>

      <Text style={styles.footer}>
        Generated by Business Partner AI • Professional DPR Generator
      </Text>

    </Page>
  </Document>
);

export default function DPRPage() {

  const [businessName, setBusinessName] = useState('');
  const [ownerName, setOwnerName] = useState('');
  const [businessType, setBusinessType] = useState('');
  const [location, setLocation] = useState('');
  const [projectCost, setProjectCost] = useState('');
  const [loanAmount, setLoanAmount] = useState('');
  const [turnover, setTurnover] = useState('');

  return (
    <div className="min-h-screen bg-black p-8 text-white">

      <div className="mx-auto max-w-5xl rounded-3xl border border-cyan-500/20 bg-slate-950 p-8 shadow-2xl">

        <h1 className="mb-3 text-4xl font-bold text-cyan-400">
          Professional DPR Generator
        </h1>

        <p className="mb-8 text-slate-400">
          Generate CA-level business project reports instantly.
        </p>

        <div className="grid gap-5 md:grid-cols-2">

          <input
            type="text"
            placeholder="Business Name"
            value={businessName}
            onChange={(e) => setBusinessName(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Owner Name"
            value={ownerName}
            onChange={(e) => setOwnerName(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Business Type"
            value={businessType}
            onChange={(e) => setBusinessType(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Business Location"
            value={location}
            onChange={(e) => setLocation(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Project Cost"
            value={projectCost}
            onChange={(e) => setProjectCost(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Loan Amount"
            value={loanAmount}
            onChange={(e) => setLoanAmount(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

          <input
            type="text"
            placeholder="Expected Annual Turnover"
            value={turnover}
            onChange={(e) => setTurnover(e.target.value)}
            className="rounded-xl border border-cyan-500/20 bg-slate-900 p-4 outline-none"
          />

        </div>

        <div className="mt-8">

          <PDFDownloadLink
            document={
              <DPRDocument
                businessName={businessName}
                ownerName={ownerName}
                businessType={businessType}
                location={location}
                projectCost={projectCost}
                loanAmount={loanAmount}
                turnover={turnover}
              />
            }
            fileName={`${businessName}-Professional-DPR.pdf`}
            className="inline-flex rounded-xl bg-cyan-400 px-6 py-4 font-bold text-black"
          >
            {({ loading }) =>
              loading
                ? 'Generating PDF...'
                : 'Download Professional DPR'
            }
          </PDFDownloadLink>

        </div>

      </div>

    </div>
  );
}