import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from '@react-pdf/renderer';

import { useState } from 'react';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
    color: '#111827',
  },

  title: {
    fontSize: 28,
    marginBottom: 20,
    fontWeight: 'bold',
    color: '#0f172a',
  },

  heading: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    fontWeight: 'bold',
    color: '#0891b2',
  },

  section: {
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },

  label: {
    fontWeight: 'bold',
  },

  paragraph: {
    lineHeight: 1.7,
    marginTop: 5,
  },

  box: {
    marginTop: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
  },

  footer: {
    marginTop: 40,
    fontSize: 10,
    color: '#6b7280',
    textAlign: 'center',
  },
});

const DPRDocument = ({
  businessName,
  ownerName,
  projectCost,
  loanAmount,
  details,
}: any) => (
  <Document>
    <Page size="A4" style={styles.page}>

      {/* Cover */}
      <Text style={styles.title}>
        Detailed Project Report
      </Text>

      <View style={styles.section}>
        <Text>
          <Text style={styles.label}>Business Name: </Text>
          {businessName}
        </Text>

        <Text>
          <Text style={styles.label}>Owner Name: </Text>
          {ownerName}
        </Text>

        <Text>
          <Text style={styles.label}>Project Cost: </Text>
          ₹ {projectCost}
        </Text>

        <Text>
          <Text style={styles.label}>Loan Amount: </Text>
          ₹ {loanAmount}
        </Text>
      </View>

      {/* Executive Summary */}
      <Text style={styles.heading}>
        Executive Summary
      </Text>

      <Text style={styles.paragraph}>
        This Detailed Project Report has been prepared for
        establishing and scaling the business venture with
        financial sustainability, operational growth and
        long-term profitability.
      </Text>

      {/* Business Overview */}
      <Text style={styles.heading}>
        Business Overview
      </Text>

      <View style={styles.box}>
        <Text style={styles.paragraph}>
          {details}
        </Text>
      </View>

      {/* Market Analysis */}
      <Text style={styles.heading}>
        Market Analysis
      </Text>

      <Text style={styles.paragraph}>
        The current market demonstrates significant demand
        growth, scalable customer acquisition opportunities
        and increasing industry adoption.
      </Text>

      {/* Financial Analysis */}
      <Text style={styles.heading}>
        Financial Projections
      </Text>

      <View style={styles.box}>
        <Text>• Estimated ROI: 28%</Text>
        <Text>• Break-even Period: 18 Months</Text>
        <Text>• Gross Margin: 42%</Text>
        <Text>• Expected Revenue Growth: 35% Yearly</Text>
      </View>

      {/* Loan Analysis */}
      <Text style={styles.heading}>
        Loan & Repayment Analysis
      </Text>

      <Text style={styles.paragraph}>
        Based on the proposed business model and projected
        revenues, the project demonstrates strong repayment
        capacity and financial feasibility.
      </Text>

      {/* Conclusion */}
      <Text style={styles.heading}>
        Conclusion
      </Text>

      <Text style={styles.paragraph}>
        The proposed business project is financially viable,
        operationally scalable and suitable for MSME and
        institutional funding support.
      </Text>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by Business Partner AI • CEO & Founder
        Akash Agnihotri
      </Text>

    </Page>
  </Document>
);

export const DPRPage = () => {
  const [businessName, setBusinessName] = useState('');
  const [ownerName, setOwnerName] = useState('');
  const [projectCost, setProjectCost] = useState('');
  const [loanAmount, setLoanAmount] = useState('');
  const [details, setDetails] = useState('');

  return (
    <div className="p-6 text-white">

      <h1 className="mb-8 text-4xl font-black">
        Professional DPR Generator
      </h1>

      <div className="grid gap-8 lg:grid-cols-2">

        {/* Form */}
        <div className="rounded-2xl border border-cyan-400/20 bg-slate-900 p-6">

          <input
            type="text"
            placeholder="Business Name"
            value={businessName}
            onChange={(e) =>
              setBusinessName(e.target.value)
            }
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <input
            type="text"
            placeholder="Owner Name"
            value={ownerName}
            onChange={(e) =>
              setOwnerName(e.target.value)
            }
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <input
            type="text"
            placeholder="Project Cost"
            value={projectCost}
            onChange={(e) =>
              setProjectCost(e.target.value)
            }
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <input
            type="text"
            placeholder="Loan Amount"
            value={loanAmount}
            onChange={(e) =>
              setLoanAmount(e.target.value)
            }
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <textarea
            placeholder="Business Details"
            value={details}
            onChange={(e) =>
              setDetails(e.target.value)
            }
            className="mb-4 h-40 w-full rounded-lg bg-slate-800 p-3"
          />

          <PDFDownloadLink
            document={
              <DPRDocument
                businessName={businessName}
                ownerName={ownerName}
                projectCost={projectCost}
                loanAmount={loanAmount}
                details={details}
              />
            }
            fileName="Professional-DPR.pdf"
          >
            {({ loading }) => (
              <button className="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-black">
                {loading
                  ? 'Generating PDF...'
                  : 'Download Professional DPR'}
              </button>
            )}
          </PDFDownloadLink>
        </div>

        {/* Preview */}
        <div className="rounded-2xl border border-cyan-400/20 bg-slate-900 p-6">
          <h2 className="mb-4 text-2xl font-bold">
            DPR Preview
          </h2>

          <div className="space-y-3 text-slate-300">
            <p>
              <strong>Business:</strong>{' '}
              {businessName || 'Your Business'}
            </p>

            <p>
              <strong>Owner:</strong>{' '}
              {ownerName || 'Owner Name'}
            </p>

            <p>
              <strong>Project Cost:</strong>{' '}
              ₹ {projectCost || '0'}
            </p>

            <p>
              <strong>Loan Amount:</strong>{' '}
              ₹ {loanAmount || '0'}
            </p>

            <p>
              <strong>Details:</strong>{' '}
              {details || 'Business description'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};