import { useRef, useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const DPRPage = () => {
  const pdfRef = useRef<HTMLDivElement>(null);

  const [businessName, setBusinessName] = useState('');
  const [projectCost, setProjectCost] = useState('');
  const [details, setDetails] = useState('');

  const generatePDF = async () => {
    if (!pdfRef.current) return;

    const canvas = await html2canvas(pdfRef.current);

    const imgData = canvas.toDataURL('image/png');

    const pdf = new jsPDF('p', 'mm', 'a4');

    const pdfWidth = pdf.internal.pageSize.getWidth();

    const pdfHeight =
      (canvas.height * pdfWidth) / canvas.width;

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);

    pdf.save(`${businessName || 'DPR-Report'}.pdf`);
  };

  return (
    <div className="p-6 text-white">
      <h1 className="mb-6 text-4xl font-bold">
        DPR Report Generator
      </h1>

      <div className="grid gap-6 lg:grid-cols-2">

        {/* Form */}
        <div className="rounded-2xl border border-cyan-400/20 bg-slate-900 p-6">
          <input
            type="text"
            placeholder="Business Name"
            value={businessName}
            onChange={(e) => setBusinessName(e.target.value)}
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <input
            type="text"
            placeholder="Project Cost"
            value={projectCost}
            onChange={(e) => setProjectCost(e.target.value)}
            className="mb-4 w-full rounded-lg bg-slate-800 p-3"
          />

          <textarea
            placeholder="Business Details"
            value={details}
            onChange={(e) => setDetails(e.target.value)}
            className="mb-4 h-40 w-full rounded-lg bg-slate-800 p-3"
          />

          <button
            onClick={generatePDF}
            className="rounded-lg bg-cyan-400 px-6 py-3 font-bold text-black"
          >
            Generate PDF DPR
          </button>
        </div>

        {/* DPR Preview */}
        <div
          ref={pdfRef}
          className="rounded-2xl bg-white p-8 text-black"
        >
          <h1 className="mb-4 text-3xl font-bold">
            Detailed Project Report
          </h1>

          <p className="mb-2">
            <strong>Business Name:</strong>{' '}
            {businessName || 'Your Business'}
          </p>

          <p className="mb-2">
            <strong>Project Cost:</strong>{' '}
            {projectCost || '₹0'}
          </p>

          <p className="mt-6 text-lg font-bold">
            Business Overview
          </p>

          <p className="mt-2 text-sm leading-7">
            {details ||
              'Professional MSME business project report generated using Business Partner AI.'}
          </p>

          <div className="mt-10">
            <h2 className="mb-2 text-xl font-bold">
              Financial Highlights
            </h2>

            <ul className="list-disc pl-6">
              <li>Projected Revenue Growth</li>
              <li>Break-even Analysis</li>
              <li>ROI Estimation</li>
              <li>Loan Eligibility</li>
              <li>Business Expansion Potential</li>
            </ul>
          </div>

          <div className="mt-10 border-t pt-4 text-sm">
            Generated by Business Partner AI
          </div>
        </div>
      </div>
    </div>
  );
};